spring.application.name=kotlin-backend

server.port=8081

#Database access
spring.datasource.url=jdbc:postgresql://localhost:6543/kotlin_db
spring.datasource.username=feature
spring.datasource.password=feature
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true